/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carlos_Imp;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Señor C.
 */
public class Estadistica_Helper extends javax.swing.JFrame {

    Secuencia secu = new Secuencia();

    /**
     * Creates new form Estadistica_Helper
     */
    public Estadistica_Helper() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ESTADÍSTICA HELPER");
//        this.setIconImage(iconoPropio);  //esto es para ponerle un icono a la ventana
        setExtendedState(JFrame.MAXIMIZED_BOTH); // y esto es para que cuando se inicie , lo haga con la ventana maximizada

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemSecueniaN = new javax.swing.JMenuItem();
        jMenuItemTablaF = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuInformacion = new javax.swing.JMenu();
        jMenuItemVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(300, 300));

        jPanelPantalla.setBackground(new java.awt.Color(18, 18, 18));
        jPanelPantalla.setPreferredSize(new java.awt.Dimension(646, 390));
        jPanelPantalla.setLayout(new javax.swing.BoxLayout(jPanelPantalla, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 187, 186));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> <center>Bienvenida/o <p> a <center> <p> -Estadística Helper- <p> :)<html>");
        jPanelPantalla.add(jLabel1);

        jMenuBar.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar.setBorder(null);

        jMenuArchivo.setText("Archivo");

        jMenuItemSecueniaN.setText("Secuencia de Números");
        jMenuItemSecueniaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSecueniaNActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSecueniaN);

        jMenuItemTablaF.setText("Tabla de Frecuencia");
        jMenuItemTablaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaFActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemTablaF);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar.add(jMenuArchivo);

        jMenuInformacion.setText("Información");

        jMenuItemVersion.setText("Número de Version");
        jMenuItemVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVersionActionPerformed(evt);
            }
        });
        jMenuInformacion.add(jMenuItemVersion);

        jMenuBar.add(jMenuInformacion);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSecueniaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSecueniaNActionPerformed
        // TODO add your handling code here:
        jPanelPantalla.removeAll();
        jPanelPantalla.add(secu);
        jPanelPantalla.repaint();
        jPanelPantalla.validate();
    }//GEN-LAST:event_jMenuItemSecueniaNActionPerformed

    private void jMenuItemTablaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemTablaFActionPerformed

    private void jMenuItemVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVersionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "-Estadística Helper-\nAlpha 0.1\n;)", "Versión", 1);
    }//GEN-LAST:event_jMenuItemVersionActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadistica_Helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadistica_Helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadistica_Helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadistica_Helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadistica_Helper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuInformacion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSecueniaN;
    private javax.swing.JMenuItem jMenuItemTablaF;
    private javax.swing.JMenuItem jMenuItemVersion;
    private javax.swing.JPanel jPanelPantalla;
    // End of variables declaration//GEN-END:variables

}
